### PR TITLE
concurrency check

### PR DESCRIPTION
**Pull request by padmanabanravikumar**
concurrency check implementation

### CODE REVIEW

**Comment by padmanabanravikumar** [comment]
fixes issue #99

**Comment by larsbj1988** [comment]
@MoonStorm 
Merge please 👍

**Comment by juzamdjinn** [comment]
Hi, where can i find examples about this implementation ?

**Comment by MoonStorm** [comment]
We appreciate the PR however we think this is outside the scope of this library.

**Pull request closed without merging**
