### PR TITLE
Add schema qualifier

### PR DESCRIPTION
**Pull request by alexisread**
Add schema qualifier to allow generation on table name clashes for differing schema.

### CODE REVIEW

**Comment by alexisread** [comment]
Thought this might be useful as you can place all generated tables/views within a single namespace, even with name clashes.

**Comment by dallasbeek** [comment]
Yes, this is the first thing I saw missing in the generated code.  Thank you alixisread.  Please accept this merge.

**Comment by dallasbeek** [comment]
Don't merge this, needs to undo the class naming.  for those peeps that have table names in multiple schemas they can use the 			
tables["tablename"].ClassName = "newname";

but I do agree that schemas should be supported by the generator.

**Comment by alexisread** [comment]
Hi, apologies for taking a while on this - I've reverted the ClassName for compatibility. Hope that's ok to get this accepted?
Thanks.

**Comment by MoonStorm** [comment]
Playing around with it more, I don't believe assigning entities to schemas from the generator is a good idea. Entities can be tweaked later if needed.

**Comment by MoonStorm** [comment]
Decided to add the feature as an opt-in flag so it won't break existing generations. The flag will set the Schema property in the Table attribute. See #198

**Pull request closed without merging**
